### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by F43nd1r** [F43nd1r/Acrarium#29]
List of UI elements that need reworking. Feel free to discuss not listed items in here.
- [x] top right menu
- [x] top right menu in dark theme
- [x] persistent dark theme - ~~waiting for https://github.com/vaadin/flow/issues/2740~~ solved using cookies instead
- [x] grid column sizing - waiting for https://github.com/vaadin/vaadin-grid/issues/1233
- [x] header on small screens
- [x] popups
- [x] proguard card
- [x] Number Input Style - waiting for https://github.com/vaadin/vaadin-text-field/issues/273 
- [x] grid initial sort - waiting for https://github.com/vaadin/vaadin-grid-flow/issues/465

**Comment by F43nd1r** [comment]
- [ ] nicer urls - waiting for https://github.com/vaadin/flow/issues/2740
- [ ] grid middle click to open in new tab - waiting for https://github.com/vaadin/vaadin-grid-flow/issues/366#
